### ISSUE TITLE
[Bug]: Custom Payloads error failing to join world after creation on latest mod version.

### ISSUE THREAD

**Issue by Harkan-Cross** [someaddons/connectivity#121]
### Describe the bug you're experiencing

The error only occurs when joining into the world, I have diagnosed that electrodynamics is the problem by looking in the debug folder. But I am hoping someone can give me some way to fix this issue I don't wanna have too remove electrodynamics.

### Reproducability

Start game with version 1.21-6.6 Neoforge.

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://gist.github.com/SefalonZophry/fc0bd7a2d4c8a9bb0c4e42c5a2f483d8

**Comment by someaddons** [comment]
should be fixed in 6.7

**Comment by Harkan-Cross** [comment]
Sadly I just tried it and it did not fix it, it is still giving the same error same cause "electrodynamics".

New Log:
https://gist.github.com/SefalonZophry/c3473d45ce064dc470ffb7defa5a9ea6

**Comment by someaddons** [comment]
ah ye this is actually an error specific to electrodynamics, they're sending a modlist in a string, and once you reach a certain amount of mods the string gets too big to be encoded, see: https://github.com/aurilisdev/Electrodynamics/issues/293
Closing this then since its mod specific^^
